{
 "title": "Cilium Metrics / API",
 "description": "Dashboard for Cilium (https://cilium.io/) metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": "label_values(kube_pod_created{pod=~\"^cilium-[a-z|A-Z|0-9]+$\"},pod)"
   }
  ]
 },
 "panels": [
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "API call latency (average node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_agent_api_process_time_seconds_sum{k8s_app=\"cilium\"}[1m])/rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "API call latency (max node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(cilium_agent_api_process_time_seconds_sum{k8s_app=\"cilium\"}[1m])/rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "# API calls (average node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, method, path)",
     "legendFormat": "{{method}} {{path}} "
    }
   ]
  },
  {
   "title": "# API calls (max node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "max(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, method, path)",
     "legendFormat": "{{method}} {{path}} "
    }
   ]
  },
  {
   "title": "API return codes (average node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, method, path, return_code)",
     "legendFormat": "{{return_code}} ({{method}} {{path}} )"
    }
   ]
  },
  {
   "title": "API return codes (sum all nodes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, method, path, return_code)",
     "legendFormat": "{{return_code}} ({{method}} {{path}} )"
    }
   ]
  }
 ]
}