{
 "title": "Cilium Metrics / Generic",
 "description": "Dashboard for Cilium (https://cilium.io/) metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": "label_values(kube_pod_created{pod=~\"^cilium-[a-z|A-Z|0-9]+$\"},pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Errors & Warnings",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_errors_warnings_total{k8s_app=\"cilium\"}[1m])) by (pod, level) * 60",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "CPU Usage per node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "min(irate(cilium_process_cpu_seconds_total{k8s_app=\"cilium\"}[1m])) by (pod) * 100",
     "legendFormat": "min"
    },
    {
     "expr": "avg(irate(cilium_process_cpu_seconds_total{k8s_app=\"cilium\"}[1m])) by (pod) * 100",
     "legendFormat": "avg"
    },
    {
     "expr": "max(irate(cilium_process_cpu_seconds_total{k8s_app=\"cilium\"}[1m])) by (pod) * 100",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Generic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Virtual Memory Bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "min(cilium_process_virtual_memory_bytes{k8s_app=\"cilium\"})",
     "legendFormat": "Min Virtual Memory"
    },
    {
     "expr": "avg(cilium_process_virtual_memory_bytes{k8s_app=\"cilium\"})",
     "legendFormat": "Average Virtual Memory"
    },
    {
     "expr": "max(cilium_process_virtual_memory_bytes{k8s_app=\"cilium\"})",
     "legendFormat": "Max Virtual Memory"
    }
   ]
  },
  {
   "title": "Resident memory status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(cilium_process_resident_memory_bytes{k8s_app=\"cilium\"})",
     "legendFormat": "AVG_resident_memory_bytes"
    },
    {
     "expr": "max(cilium_process_resident_memory_bytes{k8s_app=\"cilium\"})",
     "legendFormat": "MAX_resident_memory_bytes_max"
    },
    {
     "expr": "min(cilium_process_resident_memory_bytes{k8s_app=\"cilium\"})",
     "legendFormat": "MIN_resident_memory_bytes_min"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cilium_process_open_fds{k8s_app=\"cilium\"})",
     "legendFormat": "all nodes"
    },
    {
     "expr": "min(cilium_process_open_fds{k8s_app=\"cilium\"})",
     "legendFormat": "min/node"
    },
    {
     "expr": "avg(cilium_process_open_fds{k8s_app=\"cilium\"})",
     "legendFormat": "avg/node"
    },
    {
     "expr": "max(cilium_process_open_fds{k8s_app=\"cilium\"})",
     "legendFormat": "max/node"
    }
   ]
  },
  {
   "title": "System-wide BPF memory usage",
   "type": "graph",
   "description": "BPF memory usage in the entire system including components not managed by Cilium.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(cilium_bpf_maps_virtual_memory_max_bytes{k8s_app=\"cilium\"} + cilium_bpf_progs_virtual_memory_max_bytes{k8s_app=\"cilium\"})",
     "legendFormat": "AVG_bpf_memory_bytes_avg"
    },
    {
     "expr": "max(cilium_bpf_maps_virtual_memory_max_bytes{k8s_app=\"cilium\"} + cilium_bpf_progs_virtual_memory_max_bytes{k8s_app=\"cilium\"})",
     "legendFormat": "MAX_bpf_memory_bytes_max"
    },
    {
     "expr": "min(cilium_bpf_maps_virtual_memory_max_bytes{k8s_app=\"cilium\"} + cilium_bpf_progs_virtual_memory_max_bytes{k8s_app=\"cilium\"})",
     "legendFormat": "MIN_bpf_memory_bytes_min"
    }
   ]
  }
 ]
}