{
 "title": "Cilium Metrics / Endpoints",
 "description": "Dashboard for Cilium (https://cilium.io/) metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": "label_values(kube_pod_created{pod=~\"^cilium-[a-z|A-Z|0-9]+$\"},pod)"
   }
  ]
 },
 "panels": [
  { "title": "Endpoints", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 } },
  {
   "title": "Endpoint regeneration time (90th percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.90, rate(cilium_endpoint_regeneration_time_stats_seconds_bucket{k8s_app=\"cilium\", scope!=\"total\"}[5m]))) by (scope)",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Endpoint regeneration time (99th percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 145 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99, rate(cilium_endpoint_regeneration_time_stats_seconds_bucket{k8s_app=\"cilium\", scope!=\"total\"}[5m]))) by (scope)",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Endpoint regenerations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 154 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_endpoint_regenerations_total{k8s_app=\"cilium\"}[30s])) by(outcome)",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Cilium endpoint state",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 154 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cilium_endpoint_state{k8s_app=\"cilium\"}) by (endpoint_state)",
     "legendFormat": "{{endpoint_state}}"
    }
   ]
  }
 ]
}