{
 "title": "Cilium Metrics / kvstore",
 "description": "Dashboard for Cilium (https://cilium.io/) metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": "label_values(kube_pod_created{pod=~\"^cilium-[a-z|A-Z|0-9]+$\"},pod)"
   }
  ]
 },
 "panels": [
  { "title": "kvstore", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "# operations (sum all nodes)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kvstore_operations_total{kubernetes_pod_name=~\"$pod\"}[1m])) by (pod, scope, action)",
     "legendFormat": "{{scope}} {{action}}"
    }
   ]
  },
  {
   "title": "# operations (max node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "max(rate(kvstore_operations_total{kubernetes_pod_name=~\"$pod\"}[1m])) by (pod, scope, action)",
     "legendFormat": "{{scope}} {{action}}"
    }
   ]
  },
  {
   "title": "latency (average node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, avg(rate(cilium_kvstore_operations_duration_seconds_sum{kubernetes_pod_name=~\"$pod\"}[1m])) by (pod, action, scope) / avg(rate(cilium_kvstore_operations_duration_seconds_count{kubernetes_pod_name=~\"$pod\"}[1m])) by (pod, action, scope))",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "latency (max node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max(rate(cilium_kvstore_operations_duration_seconds_sum{kubernetes_pod_name=~\"$pod\"}[1m])) by (pod, action, scope) / avg(rate(cilium_kvstore_operations_duration_seconds_count{kubernetes_pod_name=~\"$pod\"}[1m])) by (pod, action, scope))",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "Events received (average node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kvstore_events_queue_seconds_count{kubernetes_pod_name=~\"$pod\"}[1m])) by (pod, scope, action)",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  }
 ]
}