{
 "title": "Cilium Metrics / BPF",
 "description": "Dashboard for Cilium (https://cilium.io/) metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": "label_values(kube_pod_created{pod=~\"^cilium-[a-z|A-Z|0-9]+$\"},pod)"
   }
  ]
 },
 "panels": [
  { "title": "BPF", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "# system calls (average node)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_bpf_syscall_duration_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "# system calls (max node)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "max(rate(cilium_bpf_syscall_duration_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "system call latency (avg node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_bpf_syscall_duration_seconds_sum{k8s_app=\"cilium\"}[1m])/ rate(cilium_bpf_syscall_duration_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "system call latency (max node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(cilium_bpf_syscall_duration_seconds_sum{k8s_app=\"cilium\"}[1m])/ rate(cilium_bpf_syscall_duration_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "map ops (average node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(5, avg(rate(cilium_bpf_map_ops_total{k8s_app=\"cilium\"}[5m])) by (pod, map_name, operation))",
     "legendFormat": "{{map_name}} {{operation}}"
    }
   ]
  },
  {
   "title": "map ops (max node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(5, max(rate(cilium_bpf_map_ops_total{k8s_app=\"cilium\"}[5m])) by (pod, map_name, operation))",
     "legendFormat": "{{map_name}} {{operation}}"
    }
   ]
  },
  {
   "title": "map ops (sum failures)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_bpf_map_ops_total{k8s_app=\"cilium\",outcome=\"fail\"}[5m])) by (pod, map_name, operation)",
     "legendFormat": "{{map_name}} {{operation}}"
    }
   ]
  }
 ]
}