{
 "title": "Cilium Metrics / Kubernetes Integration",
 "description": "Dashboard for Cilium (https://cilium.io/) metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": "label_values(kube_pod_created{pod=~\"^cilium-[a-z|A-Z|0-9]+$\"},pod)"
   }
  ]
 },
 "panels": [
  { "title": "Kubernetes integration", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 165 } },
  {
   "title": "apiserver latency (average node)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 166 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_k8s_client_api_latency_time_seconds_sum{k8s_app=\"cilium\"}[1m])/rate(cilium_k8s_client_api_latency_time_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "apiserver latency (max node)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 166 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(cilium_k8s_client_api_latency_time_seconds_sum{k8s_app=\"cilium\"}[1m])/rate(cilium_k8s_client_api_latency_time_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "apiserver #calls (sum all nodes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 173 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_k8s_client_api_latency_time_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "apiserver calls (sum all nodes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 173 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_k8s_client_api_calls_total{k8s_app=\"cilium\"}[1m])) by (pod, method, return_code)",
     "legendFormat": "{{method}} {{return_code}}"
    }
   ]
  },
  {
   "title": "Valid, Unnecessary K8s Events Received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{k8s_app=\"cilium\", equal=\"true\", valid=\"true\"}[5m])) by (pod, scope, action)",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "Invalid, Unnecessary K8s Events Received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{k8s_app=\"cilium\", equal=\"true\", valid=\"false\"}[5m])) by (pod, scope, action)",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "Valid, Necessary K8s Events Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{k8s_app=\"cilium\", equal=\"false\", valid=\"true\"}[5m])) by (pod, scope, action, valid)",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "Invalid, Necessary K8s Events Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 187 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{k8s_app=\"cilium\", equal=\"false\", valid=\"false\"}[5m])) by (pod, scope, action)",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "CiliumNetworkPolicy Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 195 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"CiliumNetworkPolicy\"}[1m])) by (pod, action) * 60",
     "legendFormat": "{{action}} avg"
    }
   ]
  },
  {
   "title": "NetworkPolicy Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 195 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"NetworkPolicy\"}[1m])) by (pod, action) * 60",
     "legendFormat": "{{action}} avg"
    }
   ]
  },
  {
   "title": "Pod Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"Pod\"}[1m])) by (pod, action) * 60",
     "legendFormat": "{{action}} avg"
    }
   ]
  },
  {
   "title": "Node Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 202 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"Node\"}[1m])) by (pod, action) * 60",
     "legendFormat": "{{action}} avg"
    }
   ]
  },
  {
   "title": "Service Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 209 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"Service\"}[1m])) by (pod, action) * 60",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Endpoints Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 209 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"Endpoint\"}[1m])) by (pod, action) * 60",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Namespace Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 216 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"Namespace\"}[1m])) by (pod, action) * 60",
     "legendFormat": "{{action}}"
    }
   ]
  }
 ]
}